// <auto-generated />
using LRQA_ProductsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LRQA_ProductsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805152911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LRQA_ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Running Shoes",
                            Price = 129.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            Name = "Walking Boots",
                            Price = 89.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 3,
                            Name = "Flip Flops",
                            Price = 19.99m,
                            Stock = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
